# Site settings
# in the templates available like {{ site.myvariable }}.
title: La creatividad no es talento sino actitud.
email: pedro.garcia@gmail.com
brand: Pedro García
headline: Regate, Velocidad, Inteligencia y Definición
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://footballcloud.net/" # the base hostname & protocol for your site
copyright: 2019 footballcloud Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
#snapwidget: 695035
snapwidget-istagram: 695042
#snapwidget: 695035

snapwidget: 695046

# Contacts
email: pedro.garcia@gmail.com
#<!-- SnapWidget -->
#<iframe src="https://snapwidget.com/embed/695046" class="snapwidget-widget" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:480px; height:160px"></iframe>
# Tracking
#googleAnalitycsID: UA-83933844-1


theme: jekyll-theme-cayman